-- AlterTable
ALTER TABLE `TransactionCategory` MODIFY `name` ENUM('CHIFFRE_AFFAIRES', 'AUTRES_ENTREES', 'DONS_RECUS', 'DECORATION', 'SUBVENTIONS_RECUES', 'SALAIRES', 'MATIERES_PREMIERES', 'AVOCATS', 'FRAIS_COMPTABLE', 'LOCATIONS', 'FRAIS_VEHICULES', 'NOURRITURE', 'DONS_EFFECTUES', 'LOCATIONS_NON_DEDUC', 'CHARGES_VEHICULES_NON_DEDUC', 'AUTRES_NON_DEDUC', 'IMPOTS') NOT NULL;
